[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ParticleRigidityCalculationTools"
version = "1.5.19"
description = "Python library containing tools for dealing with conversions between particle energy and rigidity"
readme = "README.md"
license = { text = "CC BY-NC-SA 4.0" }
authors = [
    { name = "Space Environment and Protection Group, University of Surrey" }
]
urls = { Homepage = "https://github.com/ssc-maire/ParticleRigidityCalculationTools" }
keywords = ["space physics", "earth", "geomagnetic", "rigidity", "magnetocosmics"]
dependencies = [
    "numpy>=1.23.1",
    "pandas>=1.4.3",
]

[tool.hatch.build.targets.wheel]
force-include = { "ParticleRigidityCalculationTools.py" = "ParticleRigidityCalculationTools.py" }

[tool.hatch.build.targets.sdist]
force-include = { "ParticleRigidityCalculationTools.py" = "ParticleRigidityCalculationTools.py" }
